import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { ArticleCard, CategoryCard, SectionHeader } from "@/components/cards";
import { HairVisual } from "@/components/visual";
import { articles, categories } from "@/lib/data";

export default function KnowledgePage() {
  return <div><Header/><main className="px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><section className="rounded-[2rem] bg-radial-gold p-7 text-white shadow-soft lg:p-10"><div className="grid gap-8 lg:grid-cols-[1fr_.75fr]"><div><p className="text-xs font-extrabold uppercase tracking-[0.25em] text-champagne">Tra cứu</p><h1 className="mt-4 text-4xl font-black tracking-tight md:text-5xl">Tra cứu kỹ thuật tóc chuyên sâu</h1><p className="mt-5 max-w-2xl leading-8 text-white/65">Hàng trăm chủ đề được chọn lọc theo tình huống salon Việt: nền tóc, nhuộm màu, phủ bạc, sửa lỗi màu và phục hồi.</p><div className="mt-7 flex max-w-2xl rounded-full bg-white p-2"><input className="min-w-0 flex-1 bg-transparent px-5 text-sm text-charcoal outline-none" placeholder="Tìm kiếm chủ đề, kỹ thuật, công thức..."/><button className="rounded-full bg-champagne px-5 py-3 text-sm font-extrabold text-charcoal">Tìm kiếm</button></div></div><div className="rounded-3xl border border-champagne/25 bg-black/25 p-4"><HairVisual className="h-56" gradient="from-[#15211e] via-[#637a4d] to-[#c9a45c]" label="Chủ đề nổi bật"/><h2 className="mt-5 text-xl font-black">Sửa lỗi màu khói bị xanh rêu</h2><p className="mt-2 text-sm leading-6 text-white/60">Phân tích nguyên nhân, hướng xử lý và công thức tham khảo.</p></div></div></section><section className="mt-10"><SectionHeader title="Chủ đề phổ biến"/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{categories.map((category)=><CategoryCard key={category.title} {...category}/>)}</div></section><section className="mt-12 grid gap-8 lg:grid-cols-[280px_1fr]"><aside className="h-fit rounded-3xl bg-white p-6 shadow-soft"><h3 className="font-extrabold text-charcoal">Bộ lọc</h3>{["Danh mục","Độ khó","Thời gian đọc","Loại nội dung"].map((group)=><div key={group} className="mt-6 border-t border-black/5 pt-5"><p className="mb-3 text-sm font-extrabold text-charcoal">{group}</p>{["Tất cả","Cơ bản","Trung cấp","Nâng cao"].map((item)=><label key={item} className="mb-2 flex items-center gap-2 text-sm text-warmgray"><input type="checkbox" className="accent-champagne"/> {item}</label>)}</div>)}</aside><div><div className="mb-5 flex items-center justify-between"><p className="text-sm font-semibold text-warmgray">Hiển thị {articles.length * 2} bài viết mẫu</p><button className="rounded-full border border-black/10 px-4 py-2 text-sm font-bold">Mới nhất</button></div><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{[...articles,...articles].map((article,index)=><ArticleCard key={`${article.slug}-${index}`} article={article}/>)}</div></div></section></div></main><Footer/></div>;
}
